# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{hipe-githelper}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mark Meves"]
  s.date = %q{2009-12-02}
  s.default_executable = %q{githelper}
  s.description = %q{command-line convenience methods for git}
  s.email = %q{mark dot meves at gmail dot com}
  s.executables = ["githelper"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "History.txt",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/githelper",
     "example1.git.status",
     "hipe-githelper.gemspec",
     "lib/hipe-githelper.rb",
     "tasks/bacon.rake_",
     "test/argv.rb",
     "test/bacon_test.rb",
     "test/example1.git.status",
     "test/other_testing_frameworks/coulda.all_test_.rb",
     "test/other_testing_frameworks/riot.all_test_.rb",
     "test/other_testing_frameworks/teststrap.rb"
  ]
  s.homepage = %q{http://github.com/hipe/hipe-githelper}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{little convenience methods for git}
  s.test_files = [
    "test/argv.rb",
     "test/bacon_test.rb",
     "test/other_testing_frameworks/coulda.all_test_.rb",
     "test/other_testing_frameworks/riot.all_test_.rb",
     "test/other_testing_frameworks/teststrap.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bacon>, [">= 1.1.0"])
      s.add_runtime_dependency(%q<hipe-gorillagrammar>, [">= 0.0.1"])
    else
      s.add_dependency(%q<bacon>, [">= 1.1.0"])
      s.add_dependency(%q<hipe-gorillagrammar>, [">= 0.0.1"])
    end
  else
    s.add_dependency(%q<bacon>, [">= 1.1.0"])
    s.add_dependency(%q<hipe-gorillagrammar>, [">= 0.0.1"])
  end
end

